### ISSUE TITLE
LetsForm from Mantine not working

### ISSUE THREAD

**Issue by ghana7989** [guidone/lets-form#19]
devbox link : https://codesandbox.io/p/devbox/wpvsry?file=%2Fsrc%2Findex.js%3A14%2C33
run the above devbox to see the error.

**Comment by guidone** [comment]
Cannot see the devbox, can you share the form with this?

<img width="1327" alt="image" src="https://github.com/guidone/lets-form/assets/502519/8b987363-1604-4f13-bda7-0c059e9a2178">

**Comment by ghana7989** [comment]
@guidone sorry for that, here is the updated link - https://codesandbox.io/p/devbox/wpvsry?file=%2Fsrc%2Findex.js%3A14%2C33
