### ISSUE TITLE
Sign Up / Log In with Github error

### ISSUE THREAD

**Issue by myrddral** [guidone/lets-form#24]
Trying to sign up or log in with Github via the button from anywhere the site results in the following error: 

`{"errors":[{"message":"Invalid payload. URL \"https://designer.letsform.dev/github\" can't be used to redirect after login.","extensions":{"code":"INVALID_PAYLOAD","reason":"URL \"https://designer.letsform.dev/github\" can't be used to redirect after login"}}]}`

**Comment by guidone** [comment]
On it, thanks for the feedback

**Comment by guidone** [comment]
Fixed now.
Thanks for the feedback
