### ISSUE TITLE
js script cannot set input-text value

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#28]
only hint/placeholder/etc property can be set in form script

**Comment by ghoshorn** [comment]
in some case, like if we get value A and value B, we can automatically calculate value C, and at the same time, we shall set the value C in the form and let the users see it

**Comment by guidone** [comment]
OK, I get your point. LetsForm it's based on React Hook Form, it exposes a method to do what you're asking for.
Let me investigate, there are few point to consider like:

- check unwanted re-renders
- verify behaviour of un-controlled components with internal state
- perhaps rename current `setValue` to `setParam` and reserve the method `setValue` to set the actual values of the form

Thanks for the feedback

**Comment by guidone** [comment]
Almost there, it's under testing

**Comment by guidone** [comment]
Ok, done on `0.10.0`, took some time to write proper testing.

The method is `.setFieldValue()`, documentation will be updated shortly and also the designer.

**Comment by guidone** [comment]
[Doc site](https://letsform.dev/advanced/form-scripts) updated
