### ISSUE TITLE
besides the initialValue, suggest to add a value property for the form

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#29]
besides the `initialValue`, suggest to add a `value` property for the form, so that it can also be used as a controlled component, with more flexibility.

**Comment by guidone** [comment]
LetsForm it's based on React Hook Form and complies with its base design which is to avoid controlled components, see [here](https://react-hook-form.com/) for an explanation and [here](https://www.javascript-jedi.com/3288e29f35ea4c2a94d7b4dfabdd88a0?pvs=25) for my point of view about controlled components.

TLDR; having a fully controlled form will be a too radical change, will not implement

Thanks for the feedback

**Comment by ghoshorn** [comment]
Thanks for the quick reply. I suggest this because I also seem some method like this in other libraries, like https://jsonforms.io/faq/#how-to-update-a-field-dependent-on-another-field-in-json-forms Approach 2.
But feel free to not consider it if you have some other concerns, thanks.
