### ISSUE TITLE
jsx error when using in Create-React-App

### ISSUE THREAD

**Issue by dwitzig** [guidone/lets-form#3]
Hi, I have started a new project to test lets-form.
project has been created with Create-React-App

when I try to use the LetsForm component I get the following error 

```
ERROR in ./node_modules/lets-form/react-material-ui/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /project/path/node_modules/lets-form/react-material-ui/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (108:3):

  106 | const FormGenerator = GenerateGenerator({ Fields, Forms });
  107 | const LetsForm = ({ framework, children, ...rest}) => (
> 108 |   <FormGenerator framework="react-material-ui" {...rest}>{children}</FormGenerator>
      |   ^
  109 | );
  110 | export default LetsForm;
  111 | export * from '../helpers';
```

any advice how to proceed with CRA?
thanks

**Comment by guidone** [comment]
Seems you're importing the un-transpiled version of the library, can you show me how are you importing it?

Should be something like

```js
import LetsForm from 'lets-form/material-ui';
```

Thanks for your feedback

**Comment by dwitzig** [comment]
thank you very much @guidone 
for some reason I had  `import LetsForm from "lets-form/react-material-ui";` (must have been a auto complete)... my bad.
changing to `import LetsForm from 'lets-form/material-ui';` fix the issue
