### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by bmx-lkvarfordt** [guidone/lets-form#35]
Are there any plans to add typescript support to this library?

**Comment by guidone** [comment]
Hi @bmx-lkvarfordt, do you mean types [declarations in the package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) or porting everything to TypeScript?
Type declarations for sure it's in the roadmap

**Comment by bmx-lkvarfordt** [comment]
Mostly looking for types declarations in the package! Thanks for the quick response!

**Comment by guidone** [comment]
TypeScript support is ready, for <LetsForm>, for the DSL (<LfField />, etc) and the LetsForm schema

```js
import {
  LetsFormSchemaReactRsuite5
} from 'lets-form/react-rsuite5';

const schema: LetsFormSchemaReactRsuite5 = { 
  // ...
};
```

documentation will be available in https://letsform.dev.

Any feedback is appreciated.
