### ISSUE TITLE
Designer > Export > Package download only works on Chrome based browsers

### ISSUE THREAD

**Issue by dwitzig** [guidone/lets-form#37]
showSaveFilePicker method only works on chrome based browsers 
Ref: https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility

suggest adding warning to export tab or disabling [Export to CRA], [Export to Vite], [Export to HTML] buttons until feature is avalable

**Comment by guidone** [comment]
Fixed in LF Designer `0.9.4`.

Thanks for the feedback 🖖
