### ISSUE TITLE
Will the designer ever be embeddable?

### ISSUE THREAD

**Issue by butchmarshall** [guidone/lets-form#41]
Great project - I found it very easy to set up.

Having users go to a separate site to manage forms isn't ideal.

Are there plans to make the designer embeddedable similar to SurveyJS?

**Comment by guidone** [comment]
Thanks.

Yes, I'm working on it. Can you share more details about your possible use case?

**Comment by butchmarshall** [comment]
My ideal implementation would be a react component that acts as a controlled/uncontrolled input.  

I'd like to manage loading/saving/versioning the form schema in my backend.

```tsx
const schema = {...};

const handleSchemaChange = (updatedSchema: any) => {
};

return (
    <Designer value={schema} defaultValue={schema} onChange={handleSchemaChange} />
);
```

**Comment by guidone** [comment]
Released new version of LetsForm Designer, you can now create LetsForm Builders from the dashboard, it's under feature flag and I've enabled you.

Thanks for the feedback

**Comment by butchmarshall** [comment]
Looks great - thanks for following up!
