### ISSUE TITLE
script like `enable` cannot work for components in array

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#50]
If put some components inside an array component, the script like `enable` will not work.
Maybe need to specify both the array index(or just default to current?) and name?

Demo code:
`fields: {
      component: 'array',
      label: 'array label',
      name: 'array_history',
      layout: 'vertical',
      arrayType: 'arrayOfObject',
      fields: [
        {
          component: 'radio-group',
          label: 'Do you?',
          name: 'do_you',
          options: [
            {
              value: 'yes',
              label: 'Yes',
            },
            {
              value: 'no',
              label: 'No',
            },
          ],
          row: false,
          script:
            "if (do_you === 'yes') { enable(comment) } else { disable(comment) }",
          'react-antd': {
            optionType: 'default',
            inline: true,
          },
        },
        {
          component: 'input-text',
          label: 'Comments',
          name: 'comment',
          disabled: true,
          'react-antd': {
            fullWidth: true,
          },
        },
      ],
    }`

Error: `[LetsForm] Error in script:  Error: Field "undefined" doesn't exist in the form`

**Comment by guidone** [comment]
Hi @ghoshorn the first error I see is this

```
script: "if (do_you === 'yes') { enable('comment') } else { disable('comment') }"
```

The `enable()`, `disable()`, `hide()`, etc methods accepts a string as argument.

In that particular case the expected behaviour is to enable or disable the `comment` field of the same array element, right? In that case the fix above still doesn't work, the `comment` field name is not unique on the form. 
Let me think how to solve this.

Thanks for the feedback

**Comment by guidone** [comment]
Ok I'm giving a look at this and it's not an easy task. 
Internally methods like `enable()` work very simple: changes the internal clone of the JSON form schema and re-render.
So even if I manage to expose in the LetsForm Script a reference to the current element of the array, these simple methods just manipulate the JSON and changes are reflected to all elements of the array.

**A possible solution**
In the array component store an ephemeral status that overrides the parameters present in the JSON form schema.

In scripts of fields contained in an array also expose a new object called `arrayItem` 

```jsx
arrayItem.hide('my_field'); // hide the field 'my_field' only in the current array item
arrayItem.show('my_field'); // show the field 'my_field' only in the current array item 
arrayItem.setParam('my_field', 'my_param', 'my_value'); 
arrayItem.enable('my_field');
arrayItem.disable('my_field');
```

Cons: it introduces an internal state in a component that needs to be updated when an element of the array is added, deleted or moved

When there are complex solutions for easy problem it's worth make a step back and spend some time analyzing the problem. What are specifically the problem you're trying to solve?

**Comment by guidone** [comment]
After refactoring of validation (which involved also a refactoring of how the form is stored internally), I might have solved the problem easily.
Basically the `setParam` method, if used inside an array, only affects the (sub-)form of the array items it was executed

Check [this example](https://designer.letsform.dev/f/ab7jxk40pvw)

**Comment by guidone** [comment]
You're right, I'm able to reproduce it, on it

**Comment by guidone** [comment]
Ok, almost done, some tests to run, I'll merge tomorrow
