### ISSUE TITLE
How to programmatically add values to Array List

### ISSUE THREAD

**Issue by dwitzig** [guidone/lets-form#51]
Hi again

I have a Array list where each item is two fields (name, category)
i'm looking to programmatically add a new item {name: "aaa", category: "bbb"} to the array. 

when I try setFieldValue on a array list (see bellow) I just get an endless loop of `add [object Object] to list`

```
let new_array_values = [...values.array_list];
new_array_values.push({name: "aaa", category: "bbb"})
setFieldValue("array_list", new_array_values)
```

is it possible to add new items to an array list? 

thanks :)

**Comment by guidone** [comment]
This should be the way, it's definetely a bug let me investigate

**Comment by dwitzig** [comment]
ok thanks @guidone.
im triggering it on a field script. specifically a checkbox group.

on change I check if checkbox item is in array_list, if not add to array and update via setFieldValue

let me know if you want me to setup an example in designer

**Comment by guidone** [comment]
Hi can you send an example?

**Comment by dwitzig** [comment]
returning to this now. retested with the latest version. 
Confirming I no longer see the issue :)
thanks @guidone
