### ISSUE TITLE
script will not be executed if the field values changed by another script

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#54]
Let's say we have a component A, if I define a script inside the A, every time when I change A's value, the script will be executed.

But if I have another component B, and the script inside B will change the value of A. In this case, although the value of A also changed, but the script inside A will not be triggered.

`A form script defined inside a field, is executed only if the field changes and at first render of the form` Feel like the script should be executed as long as the value changes? Regardless of whether it is changed by the user or changed by another script?

**Comment by guidone** [comment]
You're right, definitely a bug
