### ISSUE TITLE
setFieldValue may not work properly

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#60]
Hi, sorry to disturb you again. I just found a minor issue: sometimes the `setFieldValue` may not work properly.

Description:
I have a select A: if value is 'one', set B's value to 'true'
a toggle B: if value is 'true', show C; else hide C
a input C: empty

Step 1: select A to 'one', B is still 'false', however C is shown. (issue)
Step 2: select A to 'two', B changed to 'true', C is still shown.
Step 3, toggle B to false
Step 4: select A to 'one', here is the issue: in UI B is 'true', however in 'Form values' window the B is 'false'
Step 5: input anything in input C, the 'Form values' B changes to 'true'

Here is a simple demo: https://designer.letsform.dev/f/fv83p7ihqo
And here is a gif: 
![set_value_issue](https://github.com/user-attachments/assets/8bd14184-5818-40c8-84d2-2fa73f11b932)

**Comment by guidone** [comment]
Hi @ghoshorn it should be fixed now.

And no, you're not disturbing at all, your feedback is actually really valuable, it's part of the process to refine and improve software.

🖖
